### ISSUE TITLE
Failed to use the function from_ss58check with ed25519::Public::

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate#10533]
I am trying to generate a public key associated with an address as follows from Substrate 

Code 

```rust
use sp_core::crypto::Ss58Codec;

let public_key  = ed25519::Public::from_ss58check("5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty").
      |                                          ^^^^^^^^^^^^^^ function or associated item not found in `sp_core::ed25519::Public`
```

But I am getting the error 

error[E0599]: no function or associated item named `from_ss58check` found for struct `sp_core::ed25519::Public` in the current scope

Run time versions 
```
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.58.0-nightly (495322d77 2021-11-08)`

```
Is there a way to use `from_ss58check` ?

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/blob/master/primitives/core/src/ed25519.rs#L152-L158 here it is used.

**Comment by bkchr** [comment]
Please show your full code.

**Comment by Kalanamith** [comment]
@bkchr This is the full example https://stackoverflow.com/questions/70429492/how-to-generate-the-public-key-from-polkadot-address-from-substrate-side/70434830?noredirect=1#comment124527508_70434830

Will try this out, thanks

**Comment by bkchr** [comment]
Please report back. 

If not try `<ed25519::Public as Ss58Codec>::from_ss58check`

**Comment by Kalanamith** [comment]
@bkchr  no luck yet, its good to have some test cases around that function, especially public key addresses generated with PolkadotJS as per the stack overflow question

**Comment by bkchr** [comment]
What you mean by no luck? That it doesn't compile?
