### ISSUE TITLE
Consider Upgrading wasmtime

### ISSUE THREAD

**Issue by apopiak** [paritytech/substrate#7989]
https://github.com/bytecodealliance/wasmtime/issues/2575 keeps substrate from building on Apple M1s apparently.
I checked and it's part of the `0.22` release.

**Comment by apopiak** [comment]
depends on https://github.com/bytecodealliance/wasmtime/issues/2605

**Comment by tomaka** [comment]
https://github.com/paritytech/substrate/pull/7865
It's waiting for someone to fix the compilation errors.

Last PR was back in November, and nobody did it: https://github.com/paritytech/substrate/pull/7587

**Comment by athei** [comment]
Would I just push the fixing commits to the dependabot branch? I am asking because it seems to rebase onto master by force pushing.

**Comment by tomaka** [comment]
It stops force-pushing if you push on its branch

**Comment by jak-pan** [comment]
This won't help yet. 

I've tried to compile with the 22.1 tag from the Github repo and it's still not fixed there. 
Building with latest main branch worked so we'll need to wait still for next version I think. 

For fully working M1 build we'll also need to fix/update libsrockdb-sys though which is tracked here https://github.com/facebook/rocksdb/pull/7714 (I've successfully compiled Substrate using https://github.com/hdevalence/rust-rocksdb as another override)
