### ISSUE TITLE
build error: error[E0432]: unresolved import `node_template_runtime`

### ISSUE THREAD

**Issue by bitsrules** [paritytech/substrate#2241]
I am getting a build error 

I am using this command to build: ```substrate-node-new substrate-node-template user123```

When I just take down the newest source code of substrate it seems to build fine. 

```
   Compiling substrate-node-template-runtime-wasm v1.0.0 (/home/user/substrate-node-template/runtime/wasm)
error[E0432]: unresolved import `node_template_runtime`
 --> src/lib.rs:5:9
  |
5 | pub use node_template_runtime::*;
  |         ^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `node_template_runtime`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `substrate-node-template-runtime-wasm`.

To learn more, run the command again with --verbose.
```

**Comment by xlc** [comment]
Mostly likely caused by https://github.com/paritytech/substrate-up/pull/19
Do a global search & replace `node_template_runtime` to `user123_runtime` should fix it

I will make another PR to fix the script

**Comment by bitsrules** [comment]
Thank you @xlc
