### ISSUE TITLE
sp-keystore failed to compile in Substrate 3.0.0

### ISSUE THREAD

**Issue by chengevo** [paritytech/substrate#8427]
When added crate `sp-keystore` to a project build on top of Substrate 3.0.0, the entire project failed to build and results following errors:

```
error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
     --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.2/src/lib.rs:213:9
      |
  213 | /         compile_error!("target is not supported, for more information see: \
  214 | |                         https://docs.rs/getrandom/#unsupported-targets");
      | |_________________________________________________________________________^

     Compiling matchers v0.0.1
     Compiling arrayvec v0.4.12
  error[E0433]: failed to resolve: use of undeclared crate or module `imp`
     --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.2/src/lib.rs:235:5
      |
  235 |     imp::getrandom_inner(dest)
      |     ^^^ use of undeclared crate or module `imp`
```
## Steps to reproduce the problem
1. clone substrate-node-template project
    ```
    git clone -b v3.0.0 --depth 1 https://github.com/substrate-developer-hub/substrate-node-template
    ```
     this empty node-template project should build without problem.

2. add `sp-keystore` dependency to the project

    add `sp-keystore = { default-features = false, version = '0.9.0' }` to  `runtime/Cargo.toml`

3. build the project

     Run `cargo build --release` inside this project's root directory. It should trigger the error mentioned above

### Use different nightly build versions of Rust
I tried `nightly-2021-02-10` and `nightly-2021-03-21`, both results the same error.
### Add `js` feature to the `getrandom` crate
According to the error message, this error is result from `getrandom` failed to compile on unsupported target. The [documentation](https://docs.rs/getrandom/#unsupported-targets) of `getrandom` suggests that add `js` features should solve the problem. So I added `getrandom = {version = "0.2.1", features = ["js"]}` to `runtime/Cargo.toml`, however, the build process results more errors.

**Comment by shawntabrizi** [comment]
Can you try:

```
rustup update nightly
rustup update stable
rustup target add wasm32-unknown-unknown --toolchain nightly

**Comment by shawntabrizi** [comment]
`sp_keystore` is not compatible with the Substrate runtime as it uses STD. What are you trying to do at a high level? It probably does not make sense to include the keystore into the runtime anyway :)

**Comment by chengevo** [comment]
I'm working the [utxo project](https://github.com/substrate-developer-hub/utxo-workshop), inside which I need to [generate a public key](https://github.com/substrate-developer-hub/utxo-workshop/blob/cacc031f0de027de24f8dfa092fe9e386cefc31f/runtime/src/utxo.rs#L355-L356) for testing:
```Rust
use sp_core::testing::{KeyStore, SR25519};
let keystore = KeyStore::new(); 
let alice_pub_key = keystore.write().sr25519_generate_new(SR25519, Some(ALICE_PHRASE)).unwrap();
```
Currently this project in substrate-developer-hub still uses Substrete 2.0.0, however I'm building this project on Substrete 3.0.0. Back in Substrate 2.0.0, `KeyStore` is defined in `sp_core` crate, which have been moved to `sp-keystore` crate in 3.0.0. That's the reason I want to include `sp-keystore` into my project.

**Comment by chengevo** [comment]
You mentioned that `sp-store` requires STD, so I moved `sp-store` into the `dev-dependencies` section in `Cargo.toml`. It seems working by now.
