### ISSUE TITLE
Subkey fails to build on v1.0 branch

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#2724]
As of commit 18b6e93fb98b7eac279b18945543fae4d21da6b4 (the tip of v1.0 at time of writing) subkey build fails.

Steps to reproduce
```
git checkout 18b6e93fb98b7eac279b18945543fae4d21da6b4
cd subkey
cargo build
```

Full output:
```
error[E0405]: cannot find trait `OffchainWorkerApi` in module `offchain_primitives`
   --> node/runtime/src/lib.rs:307:28
    |
307 |     impl offchain_primitives::OffchainWorkerApi<Block> for Runtime {
    |                               ^^^^^^^^^^^^^^^^^ not found in `offchain_primitives`
help: possible candidate is found in another module, you can import it into scope
    |
23  | use offchain_primitives::runtime_decl_for_OffchainWorkerApi::OffchainWorkerApi;
    |

error[E0425]: cannot find function `offchain_worker_call_api_at` in module `offchain_primitives::runtime_decl_for_OffchainWorkerApi`
   --> node/runtime/src/lib.rs:254:1
    |
254 | / impl_runtime_apis! {
255 | |     impl client_api::Core<Block> for Runtime {
256 | |         fn version() -> RuntimeVersion {
257 | |             VERSION
...   |
357 | |     }
358 | | }
    | |_^ not found in `offchain_primitives::runtime_decl_for_OffchainWorkerApi`

error[E0425]: cannot find function `offchain_worker_native_call_generator` in module `offchain_primitives::runtime_decl_for_OffchainWorkerApi`
   --> node/runtime/src/lib.rs:254:1
    |
254 | / impl_runtime_apis! {
255 | |     impl client_api::Core<Block> for Runtime {
256 | |         fn version() -> RuntimeVersion {
257 | |             VERSION
...   |
357 | |     }
358 | | }
    | |_^ not found in `offchain_primitives::runtime_decl_for_OffchainWorkerApi`

error[E0405]: cannot find trait `AuthoritiesApi` in module `consensus_authorities`
   --> node/runtime/src/lib.rs:353:30
    |
353 |     impl consensus_authorities::AuthoritiesApi<Block> for Runtime {
    |                                 ^^^^^^^^^^^^^^ not found in `consensus_authorities`
help: possible candidate is found in another module, you can import it into scope
    |
23  | use consensus_authorities::runtime_decl_for_AuthoritiesApi::AuthoritiesApi;
    |

error[E0425]: cannot find function `authorities_call_api_at` in module `consensus_authorities::runtime_decl_for_AuthoritiesApi`
   --> node/runtime/src/lib.rs:254:1
    |
254 | / impl_runtime_apis! {
255 | |     impl client_api::Core<Block> for Runtime {
256 | |         fn version() -> RuntimeVersion {
257 | |             VERSION
...   |
357 | |     }
358 | | }
    | |_^ not found in `consensus_authorities::runtime_decl_for_AuthoritiesApi`
help: possible candidate is found in another module, you can import it into scope
    |
23  | use client::runtime_api::runtime_decl_for_Core::authorities_call_api_at;
    |

error[E0425]: cannot find function `authorities_native_call_generator` in module `consensus_authorities::runtime_decl_for_AuthoritiesApi`
   --> node/runtime/src/lib.rs:254:1
    |
254 | / impl_runtime_apis! {
255 | |     impl client_api::Core<Block> for Runtime {
256 | |         fn version() -> RuntimeVersion {
257 | |             VERSION
...   |
357 | |     }
358 | | }
    | |_^ not found in `consensus_authorities::runtime_decl_for_AuthoritiesApi`
help: possible candidate is found in another module, you can import it into scope
    |
23  | use client::runtime_api::runtime_decl_for_Core::authorities_native_call_generator;
    |

error: aborting due to 6 previous errors

Some errors occurred: E0405, E0425.
For more information about an error, try `rustc --explain E0405`.
error: Could not compile `node-runtime`.

To learn more, run the command again with --verbose.
```

Also reproduced by @laboon

**Comment by JoshOrndorff** [comment]
Same problem back at tag `v1.0.0rc2`.

**Comment by JoshOrndorff** [comment]
#2726 fixes this for me. Should we use this same issue or open a new one to request that CI build subkey?

**Comment by JoshOrndorff** [comment]
Posted a followup for the CI pipeline https://github.com/paritytech/substrate/issues/2735
