### PR TITLE
babe: restore epoch changes migration code

### LINKED ISSUE #5486: Error: Service(Client(Backend("BABE DB is corrupted. Decode error: Error decoding field EpochChanges.inner")))
I'm receiving this error after updating from 0.7.26 (maybe .25):

`Error: Service(Client(Backend("BABE DB is corrupted. Decode error: Error decoding field EpochChanges.inner")))`

I installed via cargo install `cargo install --git https://github.com/paritytech/polkadot polkadot --force --locked`

### PR DESCRIPTION
**Pull request by andresilva**
This was removed in https://github.com/paritytech/substrate/pull/5291 but it's still too early to do it as it requires nodes still on Polkadot v0.7.26 to resync from scratch.

Fixes #5486

### CODE REVIEW

**Comment by andresilva** [comment]
Check polkadot ci task failed with:
```
 error[E0432]: unresolved import `frame_support::traits::schedule`
  --> /ci-cache/substrate/cargo/check-polkadot-companion-build/git/checkouts/substrate-7e08433d4c370a21/78502f5/frame/scheduler/src/lib.rs:52:16
   |
52 |     traits::{Get, schedule},
   |                   ^^^^^^^^ no `schedule` in `traits`
```

Which is unrelated to this PR.
